### ISSUE TITLE
images

### ISSUE THREAD

**Issue by hagarmohamed71** [HelloYaoZhang/Face-Recognition-Using-PCA#1]
how to change image from colored image to grey one

**Comment by HelloYaoZhang** [comment]
As you can see my training/testing data are grayscale so I don't have to convert them.
There are buildin function  in MATLAB to convert RGB to grayscale like rgb2gray() function.

**Comment by hagarmohamed71** [comment]
From where did you get training and testing data cause I want to enlarge
data thanks in advance
